
export const POST_TRIP_DETAILS = 'POST_TRIP_DETAILS';
export const POST_TRIP_DETAILS_SUCCESS = 'POST_TRIP_DETAILS_SUCCESS';
export const POST_TRIP_DETAILS_FAILURE = 'POST_TRIP_DETAILS_FAILURE';

export const GET_ORIGIN_DETAILS = 'GET_ORIGIN_DETAILS';
export const GET_ORIGIN_DETAILS_SUCCESS = 'GET_ORIGIN_DETAILS_SUCCESS';
export const GET_ORIGIN_DETAILS_FAILURE = 'GET_ORIGIN_DETAILS_FAILURE'

export const GET_DESTINATION_DETAILS = 'GET_DESTINATION_DETAILS';
export const GET_DESTINATION_DETAILS_SUCCESS = 'GET_DESTINATION_DETAILS_SUCCESS';
export const GET_DESTINATION_DETAILS_FAILURE = 'GET_DESTINATION_DETAILS_FAILURE'